package com.schwab.assignment.artifacts;

import com.schwab.assignment.engine.*;

import org.springframework.stereotype.Component;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import java.io.IOException;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Stream;

/** Produces reviewable requirement, task, and brownfield-impact evidence under work/generated. */
@Component
public class EngineeringArtifacts {
  private final Path workspace; private final Path root; private final boolean enabled;
  @Autowired public EngineeringArtifacts(@Value("${agent.artifacts.enabled:true}") boolean enabled){this(Path.of(System.getProperty("agent.workspace.root", ".")),enabled);}
  public EngineeringArtifacts(Path workspace){this(workspace,true);}
  private EngineeringArtifacts(Path workspace,boolean enabled){this.workspace=workspace.toAbsolutePath().normalize();this.root=this.workspace.resolve("work").resolve("generated");this.enabled=enabled;}
  public static EngineeringArtifacts disabled(){return new EngineeringArtifacts(Path.of(System.getProperty("java.io.tmpdir")),false);}
  public boolean isAmbiguous(String requirement){
    String text=requirement.toLowerCase(Locale.ROOT);
    boolean requestsExpiry=text.matches(".*\\b(expire|expiration|expiry)\\b.*");
    boolean hasDuration=text.matches(".*\\b\\d+\\s*(day|days|hour|hours|month|months|year|years)\\b.*");
    boolean qualitative=text.matches(".*\\b(faster|better|improve|optimi[sz]e|scalable|reliable)\\b.*");
    boolean hasMetric=text.matches(".*\\b\\d+\\s*(ms|milliseconds?|seconds?|minutes?|hours?|days?|months?|years?|percent|%)\\b.*")||text.matches(".*\\d+\\s*(rps|requests?\\s*/\\s*second).*" );
    return (requestsExpiry&&!hasDuration)||(qualitative&&!hasMetric);
  }
  public void create(Workflow workflow){try{
    if(!enabled)return;
    Files.createDirectories(root);String id=workflow.id().toString();
    Files.writeString(root.resolve(id+"-requirement.md"),"# Requirement\n\n"+workflow.requirement()+"\n");
    Files.writeString(root.resolve(id+"-tasks.md"),"# Derived Tasks\n\n1. Understand and validate requirement\n2. Design impacted API/data flow\n3. Implement change\n4. Compile and test\n5. Update documentation\n6. Obtain release approval\n");
    if(workflow.scenario().equalsIgnoreCase("brownfield")) Files.writeString(root.resolve(id+"-impact-analysis.md"),impactAnalysis());
  }catch(IOException e){throw new IllegalStateException("could not create engineering artifacts",e);}}

  /** Static, repository-local evidence: no source is invented and no external repository is accessed. */
  private String impactAnalysis() throws IOException {
    List<SourceFile> files=scanJava(workspace);
    List<String> controllers=paths(files, f -> f.mainSource() && f.path().getFileName().toString().endsWith("Controller.java"));
    List<String> services=paths(files, f -> f.mainSource() && f.path().getFileName().toString().endsWith("Service.java"));
    List<String> entities=paths(files, f -> f.mainSource() && f.text().matches("(?sm).*^\\s*@Entity\\b.*"));
    List<String> repositories=paths(files, f -> f.mainSource() && f.path().getFileName().toString().endsWith("Repository.java"));
    List<String> tests=paths(files, f -> !f.mainSource());
    List<String> apis=apiMappings(files, workspace);
    return "# Brownfield Impact Analysis\n\n"
        + "Generated by scanning Java sources beneath `"+workspace+"`. It is an evidence artifact, not a prediction from a scenario label.\n\n"
        + section("Affected controllers",controllers)+section("Affected services",services)+section("Affected entities",entities)
        + section("Affected repositories",repositories)+section("API mappings",apis)+section("Relevant tests",tests)
        + "## Observed data flows\n\n"+observedDataFlows(files)+"\n\n"
        + "Validate existing redirect behavior, persistence of redirect counts, API response compatibility, and the listed tests before release.\n";
  }
  private String observedDataFlows(List<SourceFile> files){
    boolean controllerUsesService=files.stream().anyMatch(f->nameIs(f,"UrlController.java")&&f.text().contains("UrlService"));
    boolean serviceUsesRepository=files.stream().anyMatch(f->nameIs(f,"UrlService.java")&&f.text().contains("ShortUrlRepository"));
    boolean repositoryUsesEntity=files.stream().anyMatch(f->nameIs(f,"ShortUrlRepository.java")&&f.text().contains("ShortUrl"));
    if(controllerUsesService&&serviceUsesRepository&&repositoryUsesEntity)
      return "`UrlController -> UrlService -> ShortUrlRepository -> ShortUrl (H2)` for create, resolve/redirect, and redirect-count analytics.";
    return "_No complete controller-to-entity URL data flow was discovered from the scanned source._";
  }
  private boolean nameIs(SourceFile file,String filename){return file.path().getFileName().toString().equals(filename);}
  private List<SourceFile> scanJava(Path workspace) throws IOException {
    List<SourceFile> found=new ArrayList<>();
    for(Path sourceRoot:List.of(workspace.resolve("src/main/java"),workspace.resolve("src/test/java"))) {
      if(!Files.exists(sourceRoot)) continue;
      try(Stream<Path> paths=Files.walk(sourceRoot)) {
        for(Path path:paths.filter(p->p.toString().endsWith(".java")).toList()) found.add(new SourceFile(path,Files.readString(path)));
      }
    }
    return found;
  }
  private List<String> paths(List<SourceFile> files, java.util.function.Predicate<SourceFile> selected){return files.stream().filter(selected).map(f->relative(f.path())).sorted().toList();}
  private List<String> apiMappings(List<SourceFile> files, Path workspace){
    return files.stream().filter(f->f.mainSource() && f.text().matches("(?sm).*^\\s*@(Request|Get|Post|Put|Delete|Patch)Mapping\\b.*"))
        .map(f->workspace.relativize(f.path())+" (Spring MVC mappings)").sorted().toList();
  }
  private String section(String title,List<String> values){return "## "+title+"\n\n"+(values.isEmpty()?"_None found._":values.stream().map(v->"- `"+v+"`").collect(java.util.stream.Collectors.joining("\n")))+"\n\n";}
  private String relative(Path path){return workspace.relativize(path).toString();}
  private record SourceFile(Path path,String text) {
    boolean mainSource(){return path.toString().contains("src/main/java");}
  }
}
